### ISSUE TITLE
a window with a whole lot of nothing [Koikatsu BetterRepack X19]

### ISSUE THREAD

**Issue by RonFusaishi** [Mantas-2155X/illusion-wine-guide#15]
well atleast the koikatsu cursor properly loads, other than that its just a window with a whole lot of nothing, waited for an entire hour for something to happen but it never came, had no choice but to downgrade back to RX16.

I suspect it has something to do with the new patcher but for now i guess i'll just settle with what works for the time being.

**Comment by RonFusaishi** [comment]
Seems i manage to overcome this with a weird fix.

Instead of straight up downloading RX19 (The latest repack at the time), i download and extract RX16 and slowly work my way up to latest using the Updaters provided in the br site.

Hope this helps someone.

**Comment by Mantas-2155X** [comment]
Likely caused by either the new startup plugin (which sometimes fails to load) or game path being too long / containing special characters, or other mods/plugins.

Best to look at the `output_log.txt` file next time to determine what the issue actually is.
Feel free to reopen if you need the log analyzed
